# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='postad',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
